FROM node:18.17.0
WORKDIR /usr/src/app
COPY . /usr/src/app

ARG ELEVENLABS_API_KEY
ARG ANTHROPIC_API_KEY
ARG DB_NAME
ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASS
ARG TZ
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG AUTH_SECRET
ARG FRONTEND_URL

RUN yarn
RUN yarn build
CMD ["yarn", "start:prod"]

