name: Deploy
on:
  push:
    branches: ["master"]
jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST "https://captain.lab.foxapps.tech/api/v2/user/apps/webhooks/triggerbuild?namespace=captain&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InRva2VuVmVyc2lvbiI6IjJmMzUwMTg1LWMzMmEtNGVlYy1hMGJlLWVlZGNlNmZmM2NmZCIsImFwcE5hbWUiOiJpbW1vdHVzIiwibmFtZXNwYWNlIjoiY2FwdGFpbiJ9LCJpYXQiOjE3NDcwODk1MTN9.5RgHir1mfiJhMD-4YAa0sr2LzkknQ_N9etUq4DYWnu4"
